<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
@page{margin:12mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,Arial,sans-serif;color:#111827;margin:0}.cover{text-align:center;padding:28mm 12mm}.cover h1{font-size:32px;color:#16A34A;margin:0 0 8px}.cover .code{font-size:22px;font-weight:bold;background:#F9FAFB;border:2px solid #22C55E;border-radius:10px;padding:12px;margin:22px auto;width:70%}.cover ul{text-align:left;line-height:1.65;margin:20px auto;max-width:145mm}.page-break{page-break-after:always}.sheet{padding-top:4mm}.card{height:106mm;border:2px solid #22C55E;border-radius:12px;padding:8mm;margin-bottom:6mm;position:relative;page-break-inside:avoid}.head{border-bottom:1px solid #E5E7EB;padding-bottom:4mm;margin-bottom:4mm}.number{float:right;background:#16A34A;color:#FFFFFF;border-radius:14px;padding:4px 9px;font-weight:bold}.type{font-size:10px;font-weight:bold;color:#16A34A;text-transform:uppercase}.card h2{font-size:19px;margin:3px 0;color:#111827}.body{width:100%}.qr{width:48mm;text-align:center;vertical-align:top}.qr img{width:45mm;height:45mm}.info{padding-left:7mm;vertical-align:top;font-size:11px;line-height:1.45}.instruction{background:#F9FAFB;border-radius:7px;padding:8px;margin-bottom:8px}.meta{margin:5px 0}.points{font-size:15px;font-weight:bold;color:#F97316}.safety{position:absolute;left:8mm;right:8mm;bottom:6mm;font-size:9px;color:#4B5563;border-top:1px solid #E5E7EB;padding-top:4px}.footer{text-align:center;color:#4B5563;font-size:9px}.clear{clear:both}
</style></head><body>
<section class="cover"><h1>EcoBúsqueda</h1><h2>Kit de códigos QR permanentes</h2><div class="code">{{ $room->course?->name ?? $room->name }} · Sala {{ $room->code }}</div><p><strong>{{ $hunt->name }}</strong> · {{ $activities->count() }} actividades seleccionadas</p><ul><li>Recorta o imprime las tarjetas y ubícalas según la sugerencia.</li><li>No las instales en alturas, tableros eléctricos, zonas restringidas ni vías de evacuación.</li><li>Los códigos son permanentes y pueden reutilizarse en futuras sesiones.</li><li>Un QR solo entrega puntos cuando su actividad pertenece a una EcoBúsqueda activa.</li></ul><p class="footer">IT Conecta · Material educativo ambiental</p></section><div class="page-break"></div>
@foreach($activities->chunk(2) as $page)
<div class="sheet">
@foreach($page as $activity) @php($profile=$activity->ecoProfile)
<section class="card"><div class="head"><span class="number">#{{ $loop->parent->index*2+$loop->iteration }}</span><div class="type">{{ $profile->activity_type==='immediate'?'Acción inmediata y comprobable':'Acción previa declarada' }}</div><h2>{{ $activity->name }}</h2><div class="clear"></div></div><table class="body"><tr><td class="qr"><img src="{{ $qrImages[$activity->id] }}"><div style="font-size:8px;color:#4B5563">QR permanente</div></td><td class="info"><div class="instruction"><strong>Instrucción para el estudiante</strong><br>{{ $activity->instructions }}</div><div class="meta"><strong>Ubicación sugerida:</strong> {{ $profile->location_suggestion }}</div><div class="meta"><strong>Mensaje ambiental:</strong> {{ $activity->educational_message }}</div><div class="points">{{ $profile->game_points }} puntos</div></td></tr></table><div class="safety">Instalar en un lugar visible, accesible y seguro. No bloquear el tránsito ni incentivar acciones riesgosas.</div></section>
@endforeach
</div>
@if(!$loop->last)<div class="page-break"></div>@endif
@endforeach
</body></html>
