@extends('layouts.app')

@section('content')
@include('teacher.partials.styles')
<style>
    .faq-list{display:grid;gap:11px}.faq-item{background:var(--surface);border:1px solid var(--border);border-radius:14px;overflow:hidden}.faq-item summary{cursor:pointer;padding:17px 19px;color:var(--brand-blue-dark);font-weight:800;list-style:none;display:flex;justify-content:space-between;gap:12px}.faq-item summary::after{content:'＋';color:var(--brand-blue)}.faq-item[open] summary::after{content:'−'}.faq-answer{padding:0 19px 18px;color:var(--text-secondary);line-height:1.6;font-size:14px}.faq-answer p{margin:0 0 8px}.faq-answer ul,.faq-answer ol{margin:7px 0;padding-left:21px}.faq-answer li{margin-bottom:5px}.faq-table{width:100%;border-collapse:collapse;margin-top:9px}.faq-table th,.faq-table td{padding:8px;border:1px solid var(--border);text-align:left}.faq-table th{background:var(--info-soft);color:var(--brand-blue-dark)}
    .faq-groups{display:grid;gap:20px}.faq-group{background:var(--surface);border:1px solid var(--border);border-radius:18px;padding:20px;box-shadow:0 10px 28px color-mix(in srgb,var(--text-primary) 6%,transparent)}.faq-group.error-group{border-color:var(--danger-soft-border)}.faq-group-heading{display:flex;gap:12px;align-items:center;margin-bottom:15px}.faq-group-icon{display:flex;align-items:center;justify-content:center;width:43px;height:43px;border-radius:12px;background:var(--info-soft);font-size:21px}.error-group .faq-group-icon{background:var(--danger-soft)}.faq-group-heading .teacher-section-title{margin:0}.faq-group-heading p{margin:3px 0 0;color:var(--text-secondary);font-size:13px}.error-group .faq-item{border-color:var(--danger-soft-border)}.error-group .faq-item summary{color:var(--danger-dark)}#faqSource{display:none}@media(max-width:640px){.faq-group{padding:15px}}
</style>
<div class="teacher-shell">
    <x-breadcrumbs :items="[
        ['label' => 'Área docente', 'url' => route('teacher.dashboard')],
        ['label' => 'Instrucciones', 'url' => route('teacher.instructions')],
        ['label' => 'Preguntas frecuentes'],
    ]" />
    <div class="teacher-header"><div><p class="teacher-eyebrow">Ayuda docente</p><h1 class="teacher-title">Preguntas frecuentes</h1><p class="teacher-subtitle">Detalles de preparación, reglas y solución de problemas.</p></div><a class="teacher-btn teacher-btn-secondary" href="{{ route('teacher.instructions') }}">← Volver a instrucciones</a></div>
    <div class="faq-groups">
        <section class="faq-group"><div class="faq-group-heading"><span class="faq-group-icon">💡</span><div><h2 class="teacher-section-title teacher-section-title--brand">Información y uso</h2><p>Funcionamiento, reglas y recomendaciones para desarrollar la experiencia.</p></div></div><div class="faq-list" id="informationFaq"></div></section>
        <section class="faq-group error-group"><div class="faq-group-heading"><span class="faq-group-icon">🛠️</span><div><h2 class="teacher-section-title teacher-section-title--danger">Problemas y soluciones</h2><p>Respuestas rápidas cuando algo no funciona como se esperaba.</p></div></div><div class="faq-list" id="errorFaq"></div></section>
    </div>
    <div id="faqSource">
        <details class="faq-item" open><summary>¿Cómo preparo una clase antes de que lleguen los estudiantes?</summary><div class="faq-answer"><ol><li>Verifica que tu cuenta esté aprobada.</li><li>Crea el curso y la sala.</li><li>Revisa y selecciona las actividades.</li><li>Prepara los códigos QR.</li><li>Comprueba la conexión, Apache y MySQL de XAMPP.</li><li>Prueba el acceso desde un teléfono y los permisos de cámara.</li></ol></div></details>
        <details class="faq-item"><summary>¿Qué secuencia de clase se recomienda?</summary><div class="faq-answer"><p>Introducción ambiental, ingreso con código, cálculo de huella, comparación en cifras reales, EcoBúsqueda QR, Juego del Impostor, ranking, reflexión y cierre de la sala.</p></div></details>
        <details class="faq-item"><summary>¿Cómo preparo una EcoBúsqueda?</summary><div class="faq-answer"><p>Abre la sala, entra en “Preparar EcoBúsqueda”, asigna un nombre y selecciona entre las 20 actividades. Al guardar, queda preparada: los estudiantes pueden esperar, pero todavía no escanear ni puntuar. Descarga el kit PDF, distribuye las tarjetas y pulsa “Iniciar EcoBúsqueda”. La partida es individual, dura como máximo 15 minutos y puede finalizarse anticipadamente.</p></div></details>
        <details class="faq-item"><summary>¿Cómo funciona el tiempo y el ranking de la EcoBúsqueda?</summary><div class="faq-answer"><p>El servidor controla los 15 minutos. Al quedar cinco, el estudiante recibe un aviso. Al llegar a cero se bloquean nuevos puntos y aparece el ranking; el profesor también puede finalizar antes. Después puede reabrir la misma actividad una sola vez por 5 minutos y cerrarla manualmente cuando considere. Gana el mayor puntaje y, si existe empate, se ordena primero a quien alcanzó técnicamente ese puntaje antes.</p></div></details>
        <details class="faq-item"><summary>¿Puedo reabrir una EcoBúsqueda finalizada?</summary><div class="faq-answer"><p>Sí, mientras la sala continúe abierta. El botón “Reabrir por 5 minutos” aparece en la pantalla de control y en los resultados. Solo puede utilizarse una vez por EcoBúsqueda; conserva puntos, avances y actividades ya completadas.</p></div></details>
        <details class="faq-item"><summary>¿Por qué un QR de EcoBúsqueda no funciona?</summary><div class="faq-answer"><ul><li>La búsqueda todavía no comenzó o ya finalizó.</li><li>El QR no fue seleccionado para esa búsqueda.</li><li>La actividad o el QR están desactivados.</li><li>El estudiante ya completó ese QR durante la partida.</li></ul></div></details>
        <details class="faq-item"><summary>¿La huella de carbono es una medición certificada?</summary><div class="faq-answer"><p>No. Es una estimación educativa basada en factores definidos para interpretar hábitos. No debe utilizarse como certificación ni como una calificación personal.</p></div></details>
        <details class="faq-item"><summary>¿Por qué las alternativas aparecen en distinto orden?</summary><div class="faq-answer"><p>El orden visual cambia para reducir respuestas por patrón. Las alternativas y sus factores permanecen iguales, por lo que esto no altera el cálculo.</p></div></details>
        <details class="faq-item"><summary>¿Qué ocurre si un estudiante responde mal o se equivoca?</summary><div class="faq-answer"><p>Puede repetir la calculadora una sola vez. El segundo cálculo queda como resultado vigente. No existen más de dos intentos por estudiante dentro de la sala.</p></div></details>
        <details class="faq-item"><summary>¿Qué significa “impacto en cifras reales”?</summary><div class="faq-answer"><p>Traduce los kg CO₂e a una comparación cotidiana, como meses de electricidad de un hogar, viajes escolares, estanques de combustible o árboles capturando carbono. Son equivalencias aproximadas y muestran su fuente.</p></div></details>
        <details class="faq-item"><summary>¿Cómo vuelve a entrar un estudiante que salió?</summary><div class="faq-answer"><p>Debe escribir nuevamente el código. Si utiliza el mismo navegador y dispositivo, la sala sigue abierta y no borró sus cookies, la aplicación recuperará su identidad sin pedir otra vez el nombre.</p></div></details>
        <details class="faq-item"><summary>¿Por qué el navegador no reconoce al estudiante?</summary><div class="faq-answer"><ul><li>Cambió de dispositivo o navegador.</li><li>Utiliza navegación privada.</li><li>Eliminó cookies o datos del sitio.</li><li>La sala fue cerrada o expiró.</li></ul></div></details>
        <details class="faq-item"><summary>¿Qué hago si la cámara no abre o no reconoce el QR?</summary><div class="faq-answer"><ul><li>Autoriza la cámara cuando el navegador lo solicite. En teléfonos conectados por red local, la cámara en vivo requiere que el sitio use HTTPS.</li><li>Si rechazaste el permiso, habilítalo en los ajustes del navegador y pulsa “Reintentar cámara”.</li><li>Cierra otras aplicaciones que estén utilizando la cámara.</li><li>Mejora la iluminación, limpia el lente y utiliza “Encender linterna” si el equipo lo permite.</li><li>Siempre puedes pulsar “Tomar foto” y fotografiar el QR; cancelar esa acción no registra nada ni entrega puntos.</li><li>Utiliza un navegador actualizado y evita el modo privado.</li></ul></div></details>
        <details class="faq-item"><summary>¿Por qué una misión no entrega puntos?</summary><div class="faq-answer"><ul><li>Alguna respuesta fue incorrecta.</li><li>La actividad ya se completó ese día.</li><li>La misión no está activa o pertenece a otra sala.</li><li>La sala está cerrada.</li><li>El estudiante aún no calculó su huella.</li></ul></div></details>
        <details class="faq-item"><summary>¿Qué ocurre si una respuesta de comprobación es incorrecta?</summary><div class="faq-answer"><p>No se registra la actividad, no se entregan puntos ni reducción de CO₂ y el estudiante puede intentarlo nuevamente.</p></div></details>
        <details class="faq-item"><summary>¿Los puntos del Impostor reducen la huella?</summary><div class="faq-answer"><p>No. Son puntos de aprendizaje y participación. Solamente las actividades ambientales con factores definidos pueden representar una reducción proyectada.</p></div></details>
        <details class="faq-item"><summary>¿Cómo se determina la cantidad de impostores?</summary><div class="faq-answer"><table class="faq-table"><thead><tr><th>Estudiantes</th><th>Impostores</th></tr></thead><tbody><tr><td>3 a 7</td><td>1</td></tr><tr><td>8 a 14</td><td>2</td></tr><tr><td>15 a 22</td><td>3</td></tr><tr><td>23 a 31</td><td>4</td></tr><tr><td>32 a 40</td><td>5</td></tr></tbody></table></div></details>
        <details class="faq-item"><summary>¿Cuáles son las palabras del Juego del Impostor?</summary><div class="faq-answer"><p>Reciclaje, Compostaje, Energía solar, Huella de carbono, Biodiversidad, Reutilización, Eficiencia energética y Movilidad sostenible.</p></div></details>
        <details class="faq-item"><summary>¿Por qué el juego no comienza al entrar desde la sala?</summary><div class="faq-answer"><p>“Preparar o continuar juego” abre primero una pantalla de preparación para revisar los participantes. El reloj, la palabra y los roles se activan solamente cuando el profesor pulsa “Iniciar partida”.</p></div></details>
        <details class="faq-item"><summary>¿Cuánto dura una partida?</summary><div class="faq-answer"><p>Después de pulsar “Iniciar partida”, dura cinco minutos: cuatro para las pistas y uno para votar. Luego existe una espera de 30 segundos antes de mostrar automáticamente los resultados.</p></div></details>
        <details class="faq-item"><summary>¿Qué hace el botón “Votar ahora”?</summary><div class="faq-answer"><p>Termina inmediatamente la fase de pistas y concede exactamente un minuto completo para votar. No muestra los resultados.</p></div></details>
        <details class="faq-item"><summary>¿Cuándo aparece “Mostrar resultados”?</summary><div class="faq-answer"><p>Solamente después de cerrar el minuto de votación. Permanece durante la espera de 30 segundos. Si no se pulsa, los resultados aparecen automáticamente en las pantallas del profesor y los estudiantes.</p></div></details>
        <details class="faq-item"><summary>¿Cómo funciona la votación con varios impostores?</summary><div class="faq-answer"><p>Cada estudiante emite un solo voto. La aplicación toma tantos participantes más votados como impostores existan y compara ambos grupos. Votar por cualquiera de los impostores entrega el premio de voto correcto.</p></div></details>
        <details class="faq-item"><summary>¿Qué puntos entrega el Juego del Impostor?</summary><div class="faq-answer"><ul><li>5 puntos por enviar una pista.</li><li>10 puntos adicionales por votar por un impostor.</li><li>20 puntos para cada impostor que no sea descubierto.</li></ul></div></details>
        <details class="faq-item"><summary>¿Por qué no se registra un voto?</summary><div class="faq-answer"><ul><li>La votación todavía no comienza o ya terminó.</li><li>El estudiante ya votó.</li><li>Intentó votarse a sí mismo.</li><li>El sospechoso no pertenece a la sala.</li><li>La sala está cerrada.</li></ul></div></details>
        <details class="faq-item"><summary>¿Qué pasa si nadie vota?</summary><div class="faq-answer"><p>La partida igualmente se cierra y muestra los resultados automáticamente. Ningún estudiante recibe puntos por voto correcto.</p></div></details>
        <details class="faq-item"><summary>¿Por qué puede variar momentáneamente el contador?</summary><div class="faq-answer"><p>Una pestaña en segundo plano puede quedar suspendida por el teléfono. El tiempo oficial está guardado en el servidor; al volver o actualizar, la pantalla recupera el tiempo correcto.</p></div></details>
        <details class="faq-item"><summary>¿Por qué una prueba con muchos navegadores puede ponerse lenta?</summary><div class="faq-answer"><p>Varias ventanas en el mismo computador comparten memoria, procesador, Apache y MySQL. Para una prueba realista usa algunos dispositivos físicos, cierra pestañas antiguas y evita ejecutar otro servidor de Laravel junto con Apache.</p></div></details>
        <details class="faq-item"><summary>¿Qué información conserva el reporte?</summary><div class="faq-answer"><p>Participantes, huellas vigentes, puntos, actividades, reducciones disponibles y resultados asociados a la sala. Los registros permanecen después del cierre.</p></div></details>
        <details class="faq-item"><summary>¿Cerrar la sala elimina los resultados?</summary><div class="faq-answer"><p>No. Impide nuevos ingresos e interacciones, pero mantiene cálculos, participantes, actividades, puntos y estadísticas.</p></div></details>
        <details class="faq-item"><summary>¿Cómo mantengo la atención del curso?</summary><div class="faq-answer"><ul><li>Explica que la calculadora no entrega una nota.</li><li>Pide responder según hábitos reales.</li><li>Distribuye los QR en lugares seguros.</li><li>Evita que todos corran al mismo punto.</li><li>Explica una ronda de ejemplo antes del Impostor.</li><li>Recuerda que nadie debe mostrar su rol.</li></ul></div></details>
        <details class="faq-item"><summary>¿Cuáles son las responsabilidades del profesor?</summary><div class="faq-answer"><p>Proteger su cuenta, administrar cursos y salas, preparar QR, supervisar desplazamientos, explicar el carácter educativo, controlar el juego, revisar resultados y cerrar la sala al finalizar.</p></div></details>
    </div>
    <script>
        const faqSource = document.getElementById('faqSource');
        const informationFaq = document.getElementById('informationFaq');
        const errorFaq = document.getElementById('errorFaq');
        const errorQuestions = [
            'navegador no reconoce', 'camara no abre', 'mision no entrega puntos', 'qr de ecobusqueda no funciona',
            'no se registra un voto', 'variar momentaneamente', 'muchos navegadores'
        ];
        const normalize = text => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

        Array.from(faqSource.querySelectorAll('.faq-item')).forEach(item => {
            const question = normalize(item.querySelector('summary').textContent);
            const isError = errorQuestions.some(fragment => question.includes(fragment));
            (isError ? errorFaq : informationFaq).appendChild(item);
        });
    </script>
</div>
@endsection
