@csrf
@if(isset($activity)) @method('PUT') @endif
<div class="teacher-form-group"><label for="name">Nombre breve</label><input id="name" name="name" class="teacher-input" required maxlength="120" value="{{ old('name', $activity->name ?? '') }}" placeholder="Ej: Apagar luces del hall">@error('name')<div class="teacher-error">{{ $message }}</div>@enderror</div>
<div class="teacher-form-group"><label for="description">Descripción general</label><textarea id="description" name="description" class="teacher-input" rows="3" maxlength="500" placeholder="¿Qué hábito busca enseñar?">{{ old('description', $activity->description ?? '') }}</textarea>@error('description')<div class="teacher-error">{{ $message }}</div>@enderror</div>
<div class="teacher-form-group"><label for="instructions">Instrucción que verá el estudiante al escanear</label><textarea id="instructions" name="instructions" class="teacher-input" rows="4" required maxlength="700" placeholder="Ej: Debes apagar las luces del hall que no se estén utilizando.">{{ old('instructions', $activity->instructions ?? '') }}</textarea>@error('instructions')<div class="teacher-error">{{ $message }}</div>@enderror</div>
<div class="teacher-grid">
    <div class="teacher-form-group"><label for="category">Categoría</label><select id="category" name="category" class="teacher-input" required>@foreach(['Agua','Energía','Residuos','Transporte','Consumo','Biodiversidad','Educación','General'] as $category)<option value="{{ $category }}" @selected(old('category', $activity->category ?? '') === $category)>{{ $category }}</option>@endforeach</select>@error('category')<div class="teacher-error">{{ $message }}</div>@enderror</div>
    <div class="teacher-form-group"><label for="impact_level">Importancia y puntos</label><select id="impact_level" name="impact_level" class="teacher-input" required><option value="low" @selected(old('impact_level', $activity->impact_level ?? '') === 'low')>Bajo · 10 puntos</option><option value="medium" @selected(old('impact_level', $activity->impact_level ?? 'medium') === 'medium')>Medio · 20 puntos</option><option value="high" @selected(old('impact_level', $activity->impact_level ?? '') === 'high')>Alto · 35 puntos</option><option value="very_high" @selected(old('impact_level', $activity->impact_level ?? '') === 'very_high')>Muy alto · 50 puntos</option></select>@error('impact_level')<div class="teacher-error">{{ $message }}</div>@enderror</div>
</div>
<div class="teacher-form-group"><label for="educational_message">Mensaje educativo al completar</label><textarea id="educational_message" name="educational_message" class="teacher-input" rows="3" required maxlength="500" placeholder="Explica por qué esta acción es importante.">{{ old('educational_message', $activity->educational_message ?? '') }}</textarea>@error('educational_message')<div class="teacher-error">{{ $message }}</div>@enderror</div>
<p class="teacher-meta" style="margin-bottom:17px;">Los puntos se calculan automáticamente desde el nivel de impacto. Por ahora no se asignará una reducción de CO₂.</p>
<button class="teacher-btn teacher-btn-primary">{{ isset($activity) ? 'Guardar cambios' : 'Crear actividad' }}</button>
